theme: jekyll-theme-minimal
title: Yihan Zhang 
description: A full-stack IC (integrated circuit) engineer works on multi-disciplinery projects
author_photo: https://github.com/Shironofenny/PublicPage/blob/gh-pages/assets/author_photo.png?raw=true
